//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clalit.SeferNet.Entities
{
    using System;
    using System.Collections.Generic;
    
    [Serializable()]
    public partial class vDeptServicesRemarks
    {
        public long DeptEmployeeServiceRemarkID { get; set; }
        public int DeptCode { get; set; }
        public int ServiceCode { get; set; }
        public Nullable<int> RemarkID { get; set; }
        public string RemarkText { get; set; }
        public Nullable<bool> displayInInternet { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public byte IsMedicalTeam { get; set; }
    }
}
