//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clalit.SeferNet.Entities
{
    using System;
    using System.Collections.Generic;
    
    [Serializable()]
    public partial class vEmployeeReceptionRemarks
    {
        public string RemarkText { get; set; }
        public long EmployeeID { get; set; }
        public int EmployeeSectorCode { get; set; }
        public int receptionID { get; set; }
        public int deptCode { get; set; }
    }
}
