//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clalit.SeferNet.Entities
{
    using System;
    using System.Collections.Generic;
    
    [Serializable()]
    public partial class View_DeptDetails
    {
        public int deptCode { get; set; }
        public string deptName { get; set; }
        public Nullable<int> deptType { get; set; }
        public Nullable<int> deptLevel { get; set; }
        public string deptTypeDescription { get; set; }
        public Nullable<int> typeUnitCode { get; set; }
        public int subUnitTypeCode { get; set; }
        public string UnitTypeName { get; set; }
        public int cityCode { get; set; }
        public string cityName { get; set; }
        public string street { get; set; }
        public string house { get; set; }
        public string flat { get; set; }
        public string addressComment { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public Nullable<double> xcoord { get; set; }
        public Nullable<double> ycoord { get; set; }
        public Nullable<double> XLongitude { get; set; }
        public Nullable<double> YLatitude { get; set; }
        public Nullable<int> districtCode { get; set; }
        public Nullable<int> Simul228 { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<int> populationSectorCode { get; set; }
    }
}
