--before running MapChanges.sql script perform these 2 steps
----------------------- step 2 In the destination DB rename these tables or delete them because we'll import tables instead of them
--  x_City
--  x_Institute
--  x_Neighborhood
-- x_Street

----------------------- step 2  import these tables from source DB to destination
-- Addresses_All
--  x_City
--  x_Institute
--  x_Neighborhood
-- x_Street